# Generated by Django 4.0.3 on 2022-03-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('fathername', models.CharField(blank=True, max_length=20)),
                ('mom', models.CharField(blank=True, max_length=50)),
                ('momPhone', models.CharField(max_length=20)),
                ('dad', models.CharField(blank=True, max_length=50)),
                ('dadPhone', models.CharField(max_length=20)),
                ('birhDate', models.DateField()),
                ('sex', models.BooleanField(null=True)),
                ('grade', models.SmallIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='data/students/photo/%Y/%m/')),
                ('additional', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
