# Generated by Django 4.0.3 on 2022-03-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_student_options_alter_student_dadphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='students/photo/%Y/%m/'),
        ),
    ]
