# Generated by Django 4.0.3 on 2022-03-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='additional',
            field=models.TextField(blank=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birhDate',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dad',
            field=models.CharField(blank=True, max_length=50, verbose_name='ФИО отца'),
        ),
        migrations.AlterField(
            model_name='student',
            name='dadPhone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Тел. номер отца'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Эл. почта'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathername',
            field=models.CharField(blank=True, max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.SmallIntegerField(verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mom',
            field=models.CharField(blank=True, max_length=50, verbose_name='ФИО матери'),
        ),
        migrations.AlterField(
            model_name='student',
            name='momPhone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Тел. номер матери'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Тел. номер'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, upload_to='students/photo/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.BooleanField(null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
    ]
